#!/bin/bash

HISTFILE=~/.bash_history 

# Absolute paths to executables - Specify the versions we want to use. We don't want to use whatever is in ${PATH} (as specified in the assignment)
CAT=/usr/bin/cat
CLEAR=/usr/bin/clear
DISKFREE=/usr/bin/df
FREE=/usr/bin/free
GROUP=/usr/bin/groups
LESS=/usr/bin/less
PRINTF=/usr/bin/printf
QUOTA=/usr/bin/quota

# Use the built in for echo and exit
ECHO="command echo"
EXIT="command exit"


function showfreemem() {
	local MEMFREE

	MEMFREE=$($FREE -h 2>/dev/null)
	if [ "$MEMFREE" ]; then
		$PRINTF "\nFree memory information \n\n"
		$ECHO "${MEMFREE}"
	else
		$PRINTF "\nFailed to get free memory information.\n"
		$EXIT 3
	fi		
}

function showdiskfree() {
	local FREEDISK

	FREEDISK=$(${DISKFREE} -h 2>/dev/null)
	if [ "${FREEDISK}" ]; then
		$PRINTF "\nDisk information\n\n"
		$ECHO "${FREEDISK}"
	else
		$PRINTF "\nFailed to get disk free information.\n"
		$EXIT 3
	fi
}

function showquota() {
	local QUOTAUSAGE

	QUOTAUSAGE=$(${QUOTA} 2>/dev/null)
	if [ "${QUOTAUSAGE}" ]; then
		$PRINTF "\n Quota Information\n\n"
		$PRINTF "${QUOTAUSAGE}\n"
	else
		$PRINTF "\nNo quota information currently available.\n"
		$EXIT 3
	fi		
}

function showUSERGROUPS() {
	local USERGROUPS

	USERGROUPS=$(${GROUP} 2>/dev/null)
	if [ "${USERGROUPS}" ]; then
		$PRINTF "\nGroup information\n\n"
		$PRINTF "\n${USERGROUPS}\n"
	else
		$PRINTF "\nFailed to get the list of groups the current user is a member of.\n"
		$EXIT 3
	fi

}

function showhistory() {
	local USERHISTORY

	USERHISTORY=$(${CAT} ${HISTFILE} 2>/dev/null)
	if [ "${USERHISTORY}" ]; then
		$PRINTF "\nHistory\n"
		$ECHO "${USERHISTORY}" | ${LESS}
	else
		$PRINTF "\nFailed to obtain the history for the current user\n"
		$EXIT 3
	fi

}

function showusage() {
	$PRINTF "\nusage: $0 freemem - to show the amount of free memory available on the system"
	$PRINTF "\nusage: $0 diskfree - to show the amount of disk space free on each filesystem in the system"
	$PRINTF "\nusage: $0 quota - to show the disk quote(s) for the current user"
	$PRINTF "\nusage: $0 groups - to show the groups that the current user is a member of"
	$PRINTF "\nusage: $0 history - to show all the commands that have been entered into the current shell\n"
	$EXIT 3
}

if [ -z "$1" ]; then
	$PRINTF "\nNo arguments supplied. Usage examples are :\n"
	showusage
fi

${CLEAR}

case $1 in
 
"freemem")
	showfreemem
	;;
"diskfree")
	showdiskfree
	;;
"quota")
	showquota
	;;
"groups")
	showUSERGROUPS
	;;
"history")
	showhistory
	;;
*)
	$PRINTF "\nUnsupported argument. Usage examples are :\n"
	showusage
esac
