#!/bin/bash

 # enable history
set -o history  

HISTFILE=~/.bash_history 

# Absolute paths to executables - Specify the versions we want to use. We don't want to use whatever is in ${PATH} (as specified in the assignment)
FREE=/usr/bin/free
DISKFREE=/usr/bin/df
QUOTA=/usr/bin/quota
GROUP=/usr/bin/groups
CAT=/usr/bin/cat
CLEAR=/usr/bin/clear
PRINTF=/usr/bin/printf

# Use the built in for echo
ECHO="command echo"

function showfreemem {
	local memfree

	memfree=$($FREE -h 2>/dev/null)
	if [ "$memfree" ]; then
		$PRINTF "\nFree memory information \n\n"
		$ECHO "${memfree}"
	else
		$PRINTF "\nFailed to get free memory information.\n"
	fi		
}

function showdiskfree {
	local freedisk

	freedisk=$(${DISKFREE} -h 2>/dev/null)
	if [ "${freedisk}" ]; then
		$PRINTF "\nDisk information\n\n"
		$ECHO "${freedisk}"
	else
		$PRINTF "\nFailed to get disk free information.\n"
	fi
}

function showquota {
	local quotausage

	quotausage=$(${QUOTA} 2>/dev/null)
	if [ "${quotausage}" ]; then
		$PRINTF "\n Quota Information\n\n"
		$PRINTF "${quotausage}\n"
	else
		$PRINTF "\nNo quota information currently available.\n"
	fi		
}

function showusergroups {
	local usergroups

	usergroups=$(${GROUP} 2>/dev/null)
	if [ "${usergroups}" ]; then
		$PRINTF "\nGroup information\n\n"
		$PRINTF "\n${usergroups}\n"
	else
		$PRINTF "\nFailed to get the list of groups the current user is a member of.\n"
	fi

}

function showhistory {
	local userhistory

	userhistory=$(${CAT} ${HISTFILE} 2>/dev/null)

	if [ "${userhistory}" ]; then
		$PRINTF "\nHistory\n"
		$ECHO "${userhistory}" | more
	else
		$PRINTF "\nFailed to obtain the history for the current user\n"
	fi

}

function showusage {
	$PRINTF "\nusage: $0 freemem - to show the amount of free memory available on the system"
	$PRINTF "\nusage: $0 diskfree - to show the amount of disk space free on each filesystem in the system"
	$PRINTF "\nusage: $0 quota - to show the disk quote(s) for the current user"
	$PRINTF "\nusage: $0 groups - to show the groups that the current user is a member of"
	$PRINTF "\nusage: $0 history - to show all the commands that have been entered into the current shell\n"
}

if [ -z "$1" ]; then
	$PRINTF "\nNo arguments supplied. Usage examples are :\n"
	showusage
	exit 0
fi

${CLEAR}

case $1 in
 
"freemem")
	showfreemem
	;;
"diskfree")
	showdiskfree
	;;
"quota")
	showquota
	;;
"groups")
	showusergroups
	;;
"history")
	showhistory
	;;
*)
	$PRINTF "\nUnsupported argument. Usage examples are :\n"
	showusage
esac
