#!/bin/bash

# No globbing
set -f 


# Absolute paths to executables - Specify the versions we want to use. We don't want to use whatever is in ${PATH} (as specified in the assignment)
CAT=/usr/bin/cat
CLEAR=/usr/bin/clear
CUT=/usr/bin/cut
GREP=/usr/bin/grep
ID=/usr/bin/id
PRINTF=/usr/bin/printf

# Use the built in for exit
EXIT="command exit"

# Checks for the existence of a user. Exits this script if the user doesn't exist
function checkuser() {
	if ! "$ID" -u "$1" > /dev/null 2>&1; then
		$PRINTF "\nUser ${1} doesn't exist.\n"
		$EXIT 3
	fi

}

function showuserid() {
	local userid

	if [ "${1}" ]; then
		checkuser "$1"
		userid=$($CAT /etc/passwd 2>/dev/null | $GREP "$1" 2>/dev/null | $CUT -d':' -f 3 2>/dev/null)

		if [ "${userid}" ];then
			$PRINTF "\nThe userid is ${userid}\n"
		else
			$PRINTF "\nFailed to get the userid from /etc/passwd"
			$EXIT 3
		fi
	else
		$PRINTF "\nUser name was not specified."
		# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
		$EXIT 3
	fi
}

function showgroupid() {
	local groupid
	
	if [ "${1}" ]; then
		checkuser "$1"
		groupid=$($CAT /etc/passwd 2>/dev/null 2>/dev/null | $GREP "$1" 2>/dev/null | $CUT -d':' -f 4 2>/dev/null)
		if [ "${groupid}" ];then
			$PRINTF "\nThe groupid is ${groupid}\n"
		else
			$PRINTF "\nFailed to get the groupid from /etc/passwd"
			$EXIT 3
		fi
	else
		$PRINTF "\nUser name was not specified."
		# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
		$EXIT 3
	fi
}

function showcomment() {
	local comment
	
	if [ "${1}" ]; then
		checkuser "$1"
		comment=$($CAT /etc/passwd 2>/dev/null | $GREP "$1" 2>/dev/null | $CUT -d':' -f 5 2>/dev/null)
		if [ "${comment}" ]; then
			$PRINTF "\nThe comment is ${comment}\n"
		else
			$PRINTF "\nFailed to get the comment from /etc/passwd"
			$EXIT 3
		fi
	else
		$PRINTF "\nUser name was not specified."
		# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
		$EXIT 3
	fi
}

function showhome() {
	local home
	
	if [ "${1}" ]; then
		checkuser "$1"
		home=$($CAT /etc/passwd | $GREP "$1" | $CUT -d':' -f 6)
		if [ "${home}" ]; then
			$PRINTF "\nThe home directory is ${home}\n"
		else
			$PRINTF "\nFailed to get the home directory from /etc/passwd"
			$EXIT 3
		fi
	else
		$PRINTF "\nUser name was not specified."
		# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
		$EXIT 3
	fi
}

function showshell() {
	local shell
	
	if [ "${1}" ]; then
		checkuser "$1"
		shell=$($CAT /etc/passwd | $GREP "$1" | $CUT -d':' -f 7)
		if [ "${shell}" ]; then
			$PRINTF "\nThe shell is ${shell}\n"
		else
			$PRINTF "\nFailed to get the shell from /etc/passwd"
		fi
	else
		$PRINTF "\nUsername was not specified."
		# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
		$EXIT 3
	fi
}


function showusage() {
	$PRINTF "\nusage: $0 userid [user] - to show the userid for the user specified"
	$PRINTF "\nusage: $0 groupid [user] - to show the groupid for the user specified"
	$PRINTF "\nusage: $0 comment [user] - to any comments for the user specified"
	$PRINTF "\nusage: $0 home [user] - to show the home directory for the user specified"	
	$PRINTF "\nusage: $0 shell [user] - to show the shell for the user specified\n"	
	# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
	$EXIT 3
}

if [ -z "$1" ]; then
	$PRINTF "\nNo arguments supplied. Usage examples are :\n"
	showusage
fi

${CLEAR}

case $1 in
 
"userid")
	showuserid "$2"
	;;
"groupid")
	showgroupid "$2"
	;;
"comment")
	showcomment "$2"
	;;
"home")
	showhome "$2"
	;;
"shell")
	showshell "$2"
	;;	
*)
	$PRINTF "\nUnsupported argument. Usage examples are :\n"
	showusage
esac
