#!/bin/bash

# No globbing
set -f 


# Absolute paths to executables - Specify the versions we want to use. We don't want to use whatever is in ${PATH} (as specified in the assignment)
CAT=/usr/bin/cat
CLEAR=/usr/bin/clear
CUT=/usr/bin/cut
GREP=/usr/bin/grep
ID=/usr/bin/id
PRINTF=/usr/bin/printf

# Use the built in for exit
EXIT="command exit"

# Checks for the existence of a user. Exits this script if the user doesn't exist
function checkuser() {
	if ! "$ID" -u "$1" > /dev/null 2>&1; then
		$PRINTF "\nUser ${1} doesn't exist.\n"
		$EXIT 3
	fi

}

function showuserid() {
	local USERID

	if [ "${1}" ]; then
		checkuser "$1"
		USERID=$($CAT /etc/passwd 2>/dev/null | $GREP "$1" 2>/dev/null | $CUT -d':' -f 3 2>/dev/null)

		if [ "${USERID}" ];then
			$PRINTF "\nThe userid is ${USERID}\n"
		else
			$PRINTF "\nFailed to get the userid from /etc/passwd\n"
			$EXIT 3
		fi
	else
		$PRINTF "\nUser name was not specified.\n"
		# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
		$EXIT 3
	fi
}

function showgroupid() {
	local GROUPID
	
	if [ "${1}" ]; then
		checkuser "$1"
		GROUPID=$($CAT /etc/passwd 2>/dev/null 2>/dev/null | $GREP "$1" 2>/dev/null | $CUT -d':' -f 4 2>/dev/null)
		if [ "${GROUPID}" ];then
			$PRINTF "\nThe groupid is ${GROUPID}\n"
		else
			$PRINTF "\nFailed to get the groupid from /etc/passwd\n"
			$EXIT 3
		fi
	else
		$PRINTF "\nUser name was not specified.\n"
		# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
		$EXIT 3
	fi
}

function showcomment() {
	local COMMENT
	
	if [ "${1}" ]; then
		checkuser "$1"
		COMMENT=$($CAT /etc/passwd 2>/dev/null | $GREP "$1" 2>/dev/null | $CUT -d':' -f 5 2>/dev/null)
		if [ "${COMMENT}" ]; then
			$PRINTF "\nThe comment is ${COMMENT}\n"
		else
			$PRINTF "\nFailed to get the comment from /etc/passwd\n"
			$EXIT 3
		fi
	else
		$PRINTF "\nUser name was not specified.\n"
		# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
		$EXIT 3
	fi
}

function showhome() {
	local HOME
	
	if [ "${1}" ]; then
		checkuser "$1"
		HOME=$($CAT /etc/passwd | $GREP "$1" | $CUT -d':' -f 6)
		if [ "${HOME}" ]; then
			$PRINTF "\nThe home directory is ${HOME}\n"
		else
			$PRINTF "\nFailed to get the HOME directory from /etc/passwd\n"
			$EXIT 3
		fi
	else
		$PRINTF "\nUser name was not specified.\n"
		# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
		$EXIT 3
	fi
}

function showshell() {
	local SHELL
	
	if [ "${1}" ]; then
		checkuser "$1"
		SHELL=$($CAT /etc/passwd | $GREP "$1" | $CUT -d':' -f 7)
		if [ "${SHELL}" ]; then
			$PRINTF "\nThe shell is ${SHELL}\n"
		else
			$PRINTF "\nFailed to get the shell from /etc/passwd\n"
		fi
	else
		$PRINTF "\nUsername was not specified.\n"
		# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
		$EXIT 3
	fi
}


function showusage() {
	$PRINTF "\nusage: $0 userid [user] - to show the userid for the user specified"
	$PRINTF "\nusage: $0 groupid [user] - to show the group for the user specified"
	$PRINTF "\nusage: $0 comment [user] - to any comments for the user specified"
	$PRINTF "\nusage: $0 home [user] - to show the home directory for the user specified"	
	$PRINTF "\nusage: $0 shell [user] - to show the shell for the user specified\n"	
	# Don't use a reserved exit code http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF
	$EXIT 3
}

if [ -z "$1" ]; then
	$PRINTF "\nNo arguments supplied. Usage examples are :\n"
	showusage
fi

${CLEAR}

case $1 in
 
"userid")
	showuserid "$2"
	;;
"groupid")
	showgroupid "$2"
	;;
"comment")
	showcomment "$2"
	;;
"home")
	showhome "$2"
	;;
"shell")
	showshell "$2"
	;;	
*)
	$PRINTF "\nUnsupported argument. Usage examples are :\n"
	showusage
esac
